__author__ = 'Moveton'
import time

"""
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


start_time = time.time()

def fib(x):

    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    """

    count = 0
    a, b = 0, 1

    for i in range(x):
        a, b = b, a + b
        if a % 2 == 0:
            count += a
    return(count)

print(fib(100))
print('It took ' + str(time.time() - start_time ) + " seconds")